### ISSUE TITLE
Different table

### ISSUE THREAD

**Issue by NFLitchkey** [gavin-lindahl/gavin-testing-repo#2]
Should we be pulling from a different table?

https://github.com/gavin-lindahl/gavin-testing-repo/blob/5741703a86c104b7c3e0e06602214a16a23673f2/1_WFPC/programs/client1/client1_program.txt#L5

**Comment by gavin-lindahl** [comment]
Yes, you are right!  Good Catch!  It should be pulled from the analysis extract table:

`FROM work.t_&client_number._&medte._analysis_extract ;`

I'm going to assign this to you, can you please update, commit, and then create a pull request for me to review?  I'll check back tomorrow morning.  Have a good night!

**Comment by NFLitchkey** [comment]
Submitted pull request to correct this issue

**Comment by gavin-lindahl** [comment]
Closing the issue as the code was updated and the main has been merged
